name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and Test
      run: |
        chmod +x mvnw
        ./mvnw clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to AWS Elastic Beanstalk
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        eb init <your-elastic-beanstalk-app-name> --region <aws-region>
        eb deploy

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Rollback if needed
      run: |
        # Check if the deployment was successful; if not, perform rollback
        DEPLOY_STATUS=$(eb status | grep 'Health' | awk '{print $3}')
        if [[ "$DEPLOY_STATUS" != "Green" ]]; then
          eb terminate <your-elastic-beanstalk-environment-name>
        fi
